import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/0 - Header/Header";
import Main from "@/components/1 - Main/Main";

export const metadata: Metadata = {
  title: "Quran app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" relative my-[5px] md:my-[11px] mx-2 md:mx-5">
        {/* <Header /> */}
        <Main />
      </body>
    </html>
  );
}
